 system("egrep '^[1-2]/2/2007|Date' household_power_consumption.txt > household")
 png(filename = "plot3.png", width = 480, height = 480)
 household <- read.csv("household", sep=";")
datetime <- strptime(paste(as.Date(household$Date, format='%d/%m/%Y'), household$Time), "%Y-%m-%d %H:%M:%S")
plot(datetime, household$Sub_metering_1, type = 'l', xlab = "", ylab = "Energy sub metering")
lines(datetime, household$Sub_metering_2, col = "red")
lines(datetime, household$Sub_metering_3, col = "blue")
legend("topright",lty = c(1,1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()