 system("egrep '^[1-2]/2/2007|Date' household_power_consumption.txt > household")
 png(filename = "plot1.png", width = 480, height = 480)
 household <- read.csv("household", sep=";")
 hist(household$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)")
 dev.off()